
  full_screen = false
  window_width = 1280
  window_height = 720
  game_x = 100
  game_y = 100
  game_z = 100
  target_fps = 999
  is_resizable = true
  unit_number = 10
  unit_radius = 100
  unit_mass_multiplier = 10
  unit_initial_spacing = 0.1
  unit_elasticity = 0.8
  wall_elasticity = 0.8
  show_vectors = false
  scale_factor = 1 # 1 pixel = 1 cm
  apply_gravity = false
  gravity = 9.81
  show_quadtree = false
  show_trail = false
  should_be_profiled = true
  use_experimental_quadtree = false
  set_random_radius = true
  radius_min = 0.3
  radius_max = 0.5
  set_random_mass_multiplier = true
  mass_multiplier_min = 10
  mass_multiplier_max = 100
  set_random_elasticity = true
  elasticity_min = 0.5
  elasticity_max = 0.7
  show_overlay = true
  set_random_color = true
  show_speed_color = false
  units_emit_gravity = true
  unit_gravitational_multiplier = 0.5

  unit_transition_duration = 0.5
  cluster_threshold = 10 # minimum distance in order to create a cluster
  cluster_resistance_factor = 50000