
  full_screen = false
  window_width = 1280
  window_height = 720
  target_fps = 999
  is_resizable = true
  particle_number = 100
  particle_radius = 10
  particle_mass = 1
  particle_initial_spacing = 3
  particle_elasticity = 1
  wall_elasticity = 1
  show_vectors = false
  scale_factor = 1 # 1 pixel = 1 cm
  apply_gravity = true
  gravity = 981
  show_quadtree = true
  shot_trail = false
  should_be_profiled = true
  use_experimental_quadtree = false
  set_random_radius = true
  radius_min = 10
  radius_max = 20
  set_random_mass = true
  mass_min = 1
  mass_max = 100
  set_random_elasticity = true
  elasticity_min = 0.5
  elasticity_max = 0.9
  show_overlay = true
  set_random_color = true
  show_speed_color = true
