# simulation config
  target_fps = 999
  full_screen = false
  window_width = 1600
  window_height = 1280
  is_resizable = true
  should_be_profiled = true
  octree_max_level = 10
  max_unit_number_per_level = 2
  show_octree = true
  resolution_steps = 1
  scale_factor = 1 # 1 pixel = 1 cm
  frametime = 0.001 # 0.01 s = 100 hz

# world config
  game_x = 20
  game_y = 20
  game_z = 20
  wall_elasticity = 0.1
  apply_gravity = false
  gravity = -9.81
  
# unit config
  unit_number = 30
  unit_initial_spacing = 5
  units_emit_gravity = true
  unit_gravitational_multiplier = 1

  unit_radius = 1
  unit_radius_multiplier = 0.1
  set_random_radius = false
  radius_min = 1
  radius_max = 10
  
  unit_mass_multiplier = 10000000000000
  set_random_mass_multiplier = false
  mass_multiplier_min = 1
  mass_multiplier_max = 10
  
  unit_elasticity = 0.01
  set_random_elasticity = false
  elasticity_min = 0.5
  elasticity_max = 0.7
  

  show_vectors = true
  show_trail = false
  show_overlay = false
  set_random_color = true
  show_speed_color = false

# testing
  # test_duration = 5
  # test_iterations = 10
