# simulation config
  target_fps = 999
  full_screen = false
  window_width = 1600
  window_height = 1280
  is_resizable = true
  should_be_profiled = true
  octree_max_level = 10
  max_unit_number_per_level = 5
  resolution_steps = 1
  scale_factor = 1 # 1 pixel = 1 cm
  frametime = 10000

# world config
  game_x = 500
  game_y = 500
  game_z = 500
  wall_elasticity = 0.8
  apply_gravity = false
  gravity = -9.81
  show_octree = false
  
# unit config
  unit_number = 1000
  unit_initial_spacing = 4
  units_emit_gravity = true
  unit_gravitational_multiplier = 1

  unit_radius = 1
  unit_radius_multiplier = 0.2
  set_random_radius = true
  radius_min = 1
  radius_max = 10
  
  unit_mass_multiplier = 1
  set_random_mass_multiplier = false
  mass_multiplier_min = 1
  mass_multiplier_max = 10
  
  unit_elasticity = 0.7
  set_random_elasticity = false
  elasticity_min = 0.5
  elasticity_max = 0.7
  

  show_vectors = true
  show_trail = false
  show_overlay = false
  set_random_color = true
  show_speed_color = false

# testing
  # test_duration = 5
  # test_iterations = 10
