# simulation config
  target_fps = 999
  full_screen = false
  window_width = 1280
  window_height = 720
  is_resizable = true
  should_be_profiled = true
  octree_max_level = 8
  max_unit_number_per_level = 5
  resolution_steps = 3
  use_experimental_octree = true
  scale_factor = 1 # 1 pixel = 1 cm

# world config
  game_x = 50
  game_y = 50
  game_z = 50
  wall_elasticity = 1
  apply_gravity = true
  gravity = -9.81
  show_octree = true
  
# unit config
  unit_number = 100
  unit_initial_spacing = 0
  units_emit_gravity = false
  unit_gravitational_multiplier = 1

  unit_radius = 1
  unit_radius_multiplier = 0.2
  set_random_radius = false
  radius_min = 1
  radius_max = 5
  
  unit_mass_multiplier = 1
  set_random_mass_multiplier = false
  mass_multiplier_min = 1
  mass_multiplier_max = 10
  show_mass_color = false
  
  unit_elasticity = 1
  set_random_elasticity = false
  elasticity_min = 0.5
  elasticity_max = 0.7
  

  show_vectors = false
  show_trail = false
  show_overlay = false
  set_random_color = true
  show_speed_color = false

# testing
  test_duration = 5
  test_iterations = 10
