# simulation config
  target_fps = 999
  full_screen = false
  window_width = 1600
  window_height = 1280
  is_resizable = true
  should_be_profiled = true
  octree_max_level = 100
  max_unit_number_per_level = 2
  resolution_steps = 1
  scale_factor = 1 # 1 pixel = 1 cm

# world config
  game_x = 10
  game_y = 10
  game_z = 10
  wall_elasticity = 1
  apply_gravity = true
  gravity = -9.81
  show_octree = false
  
# unit config
  unit_number = 1
  unit_initial_spacing = 0.1
  units_emit_gravity = false
  unit_gravitational_multiplier = 1

  unit_radius = 1
  unit_radius_multiplier = 0.1
  # set_random_radius = false
  # radius_min = 1
  # radius_max = 5
  
  unit_mass_multiplier = 10
  # set_random_mass_multiplier = false
  # mass_multiplier_min = 1
  # mass_multiplier_max = 10
  # show_mass_color = false
  
  unit_elasticity = 1
  # set_random_elasticity = false
  # elasticity_min = 0.5
  # elasticity_max = 0.7
  

  show_vectors = false
  show_trail = false
  show_overlay = false
  set_random_color = false
  show_speed_color = false

# testing
  # test_duration = 5
  # test_iterations = 10
